# Generated by Django 5.0.3 on 2024-03-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument_structure', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrammClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramm_class', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiom', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Irregularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irregularity', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polysemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polysemy', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grammems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammem', models.CharField(max_length=20, unique=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.partofspeech')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=45)),
                ('link_word_str', models.CharField(max_length=45)),
                ('transcription', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('trans_ru', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('trans_eng', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('gloss', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('example', models.CharField(blank=True, max_length=200, null=True)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('class_words', models.CharField(blank=True, max_length=256, null=True)),
                ('class_words_trans', models.CharField(blank=True, max_length=256, null=True)),
                ('sound', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=50, null=True)),
                ('argument_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.argumentstructure')),
                ('gramm_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.grammclass')),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.idiom')),
                ('irregularity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.irregularity')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.origin')),
                ('polysemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.polysemy')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.partofspeech')),
                ('root_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.root')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.source')),
            ],
        ),
        migrations.CreateModel(
            name='Morpheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morpheme', models.CharField(db_index=True, max_length=45)),
                ('order_id', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('number', models.CharField(db_index=True, max_length=20)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_word', to='dictionary.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordform', models.CharField(db_index=True, max_length=45)),
                ('grammem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.grammems')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
    ]
