# Generated by Django 3.2.18 on 2024-04-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_frame', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grammems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammem', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiom', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Irregularities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irregularity', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MorphemeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morph_number', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MorphemeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morph_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polysemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polysemy', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyntacticClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syntactic_class', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_cyr', models.CharField(max_length=45)),
                ('entry_lat', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('link_cyr', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('meaning_rus', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('meaning_eng', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('gloss', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('sound', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=50, null=True)),
                ('class_words_cyr', models.CharField(blank=True, max_length=256, null=True)),
                ('class_words_lat', models.CharField(blank=True, max_length=256, null=True)),
                ('case_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.caseframe')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.gender')),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.idiom')),
                ('irregularities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.irregularities')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.origin')),
                ('polysemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.polysemy')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_class', to='dictionary.partofspeech')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.source')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.structure')),
                ('syntactic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.syntacticclass')),
            ],
        ),
        migrations.CreateModel(
            name='WordForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordform', models.CharField(db_index=True, max_length=45)),
                ('grammem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.grammems')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='Morpheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morpheme', models.CharField(db_index=True, max_length=45)),
                ('order_id', models.IntegerField()),
                ('morph_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.morphemenumber')),
                ('morph_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.morphemetype')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_word', to='dictionary.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
        ),
        migrations.AddField(
            model_name='grammems',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.partofspeech'),
        ),
    ]
