# Generated by Django 3.2.18 on 2024-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='meaning_eng',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning_rus',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
