# Generated by Django 3.2.18 on 2024-04-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20240414_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_class', to='dictionary.partofspeech'),
        ),
    ]
