# Generated by Django 3.2.18 on 2024-04-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_word_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morpheme',
            name='morph_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.morphemetype'),
        ),
    ]
