# Generated by Django 3.2.18 on 2024-04-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_morpheme_morph_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordform',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordforms', to='dictionary.word'),
        ),
    ]
