# Generated by Django 3.2.18 on 2025-01-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_wordform_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiom',
            name='rus',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word'),
        ),
        migrations.AlterField(
            model_name='link',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_word', to='dictionary.word'),
        ),
        migrations.AlterField(
            model_name='morpheme',
            name='order_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='morpheme',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morphemes', to='dictionary.word'),
        ),
        migrations.AlterField(
            model_name='morphemenumber',
            name='morph_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='morphemetype',
            name='morph_type',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='class_words_cyr',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='class_words_lat',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='entry_cyr',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='word',
            name='img',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='sound',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
