# Generated by Django 3.2.18 on 2026-04-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morpheme',
            name='morph_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.morphemenumber'),
        ),
        migrations.AlterField(
            model_name='morpheme',
            name='morph_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.morphemetype'),
        ),
        migrations.AlterField(
            model_name='word',
            name='case_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.caseframe'),
        ),
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.gender'),
        ),
        migrations.AlterField(
            model_name='word',
            name='irregularities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.irregularities'),
        ),
        migrations.AlterField(
            model_name='word',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.origin'),
        ),
        migrations.AlterField(
            model_name='word',
            name='polysemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.polysemy'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_class', to='dictionary.partofspeech'),
        ),
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.source'),
        ),
        migrations.AlterField(
            model_name='word',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.structure'),
        ),
        migrations.AlterField(
            model_name='word',
            name='syntactic_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.syntacticclass'),
        ),
    ]
