# Generated by Django 3.2.18 on 2026-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20260426_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='morphemetype',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (англ)'),
        ),
        migrations.AddField(
            model_name='morphemetype',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (рус)'),
        ),
        migrations.AddField(
            model_name='partofspeech',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (англ)'),
        ),
        migrations.AddField(
            model_name='partofspeech',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (рус)'),
        ),
    ]
